spring.application.name=Sortify_WEBAPP
spring.datasource.url=jdbc:postgresql://10.134.178.161:5432/sortify_db
spring.datasource.username=postgres
spring.datasource.password=newpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
server.address=0.0.0.0

